### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by GregPlowman** [JuliaMath/DoubleDouble.jl#20]
Is it possible to tag a new version?

I wasn't aware that PR #18 had already fixed issue #17
Also I think PR #19 was unnecessary as `zero` and `one` will work after PR #18 
This may have come about because the updates were not in released version.
If you like I can create a PR to remove explicit methods for `one` and `zero` (but of course leave the tests)
In any case, releasing a new version would be good.

**Comment by GregPlowman** [comment]
See PR #21

**Comment by dpsanders** [comment]
v0.2.1 has been tagged! Thanks.

**Comment by GregPlowman** [comment]
Thanks!
